import { defineType, defineField } from "sanity";
import { Boxes } from "lucide-react";

export default defineType({
  name: "product",
  title: "Product",
  type: "document",
  icon: Boxes,
  groups: [
    {
      name: "content",
      title: "Content",
    },
    {
      name: "seo",
      title: "SEO",
    },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      group: "content",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "content",
      options: { source: "title", maxLength: 96 },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "category",
      title: "Category",
      type: "reference",
      group: "content",
      to: [{ type: "productCategory" }],
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "excerpt",
      title: "Short description",
      type: "text",
      group: "content",
      rows: 3,
    }),
    defineField({
      name: "description",
      title: "Body",
      type: "block-content",
      group: "content",
    }),
    defineField({
      name: "images",
      title: "Images",
      type: "array",
      group: "content",
      of: [{ type: "image", options: { hotspot: true } }],
      validation: (Rule) => Rule.min(1),
    }),
    defineField({
      name: "pricePerDay",
      title: "Price per day (PLN)",
      type: "number",
      group: "content",
      validation: (Rule) => Rule.min(0),
    }),
    defineField({
      name: "deposit",
      title: "Deposit (PLN)",
      type: "number",
      group: "content",
      validation: (Rule) => Rule.min(0),
    }),
    defineField({
      name: "status",
      title: "Status",
      type: "string",
      group: "content",
      options: {
        list: [
          { title: "Available", value: "available" },
          { title: "Unavailable", value: "unavailable" },
        ],
        layout: "radio",
      },
      initialValue: "available",
    }),
    defineField({
      name: "isAddon",
      title: "Is Addon Product",
      type: "boolean",
      group: "content",
      description: "Mark this product as an addon (powerbank, cable, accessory) that can be added to main products",
      initialValue: false,
    }),
    defineField({
      name: "canBeOrderedAlone",
      title: "Can Be Ordered Alone",
      type: "boolean",
      group: "content",
      description: "If false, this addon can only be added to main products, not ordered separately",
      initialValue: false,
      hidden: ({ document }) => document?.isAddon !== true,
    }),
    defineField({
      name: "mainProducts",
      title: "Main Products",
      type: "array",
      group: "content",
      description: "Main products that this addon can be added to (e.g., Starlink Mini, Starlink Standard)",
      of: [
        {
          type: "reference",
          to: [{ type: "product" }],
          options: {
            filter: "isAddon != true",
          },
        },
      ],
      hidden: ({ document }) => document?.isAddon !== true,
    }),
    defineField({
      name: "availableAddons",
      title: "Available Addons",
      type: "array",
      group: "content",
      description: "Addon products that can be added to this main product",
      of: [
        {
          type: "reference",
          to: [{ type: "product" }],
          options: {
            filter: "isAddon == true",
          },
        },
      ],
      hidden: ({ document }) => document?.isAddon === true,
    }),
    defineField({
      name: "tags",
      title: "Tags",
      type: "array",
      group: "content",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "specs",
      title: "Specs",
      type: "array",
      group: "content",
      of: [
        {
          type: "object",
          fields: [
            defineField({ name: "label", title: "Label", type: "string" }),
            defineField({ name: "value", title: "Value", type: "string" }),
          ],
          preview: { select: { title: "label", subtitle: "value" } },
        },
      ],
    }),
    defineField({
      name: "blocks",
      title: "Blocks",
      type: "array",
      group: "content",
      of: [
        { type: "hero-1" },
        { type: "hero-2" },
        { type: "section-header" },
        { type: "split-row" },
        { type: "split-cards-list" },
        { type: "split-info-list" },
        { type: "grid-row" },
        { type: "carousel-1" },
        { type: "carousel-2" },
        { type: "feature-carousel" },
        { type: "timeline-row" },
        { type: "cta-1" },
        { type: "logo-cloud-1" },
        { type: "faqs" },
        { type: "form-newsletter" },
        { type: "all-posts" },
        { type: "rich-body" },
        { type: "blog-carousel" },
      ],
    }),
    // SEO Fields
    defineField({
      name: "meta_title",
      title: "Meta Title",
      type: "string",
      group: "seo",
    }),
    defineField({
      name: "meta_description",
      title: "Meta Description",
      type: "text",
      group: "seo",
    }),
    defineField({
      name: "noindex",
      title: "No Index",
      type: "boolean",
      initialValue: false,
      group: "seo",
    }),
    defineField({
      name: "ogImage",
      title: "Open Graph Image - [1200x630]",
      type: "image",
      group: "seo",
    }),
    defineField({
      name: "orderRank",
      title: "Order Rank",
      type: "string",
      hidden: true,
    }),
  ],
  preview: {
    select: { title: "title", media: "images.0", subtitle: "category.title" },
  },
});
